/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const TodosListLazyImport = createFileRoute('/todos/list')()
const TodosColumnsLazyImport = createFileRoute('/todos/columns')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TodosListLazyRoute = TodosListLazyImport.update({
  path: '/todos/list',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/todos/list.lazy').then((d) => d.Route))

const TodosColumnsLazyRoute = TodosColumnsLazyImport.update({
  path: '/todos/columns',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/todos/columns.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/todos/columns': {
      preLoaderRoute: typeof TodosColumnsLazyImport
      parentRoute: typeof rootRoute
    }
    '/todos/list': {
      preLoaderRoute: typeof TodosListLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  TodosColumnsLazyRoute,
  TodosListLazyRoute,
])

/* prettier-ignore-end */
